from enum import Enum, auto


class Opcode(Enum):
    value: int

    HANDSHAKE = 0
    PING = auto()
    LEVEL_BEGIN = auto()
    LEVEL_DATA = auto()
    LEVEL_END = auto()
    SET_BLOCK_CLIENT = auto()
    SET_BLOCK = auto()
    ADD_ENTITY = auto()
    ENTITY_TELEPORT = auto()
    RELPOS_AND_ORI_UPDATE = auto()
    RELPOS_UPDATE = auto()
    ORI_UPDATE = auto()
    REMOVE_ENTITY = auto()
    MESSAGE = auto()
    KICK = auto()
    SET_PERMISSION = auto()
    EXT_INFO = auto()
    EXT_ENTRY = auto()
    SET_REACH = auto()
    CUSTOM_BLOCK_LEVEL = auto()
    HOLD_THIS = auto()
    SET_TEXT_HOTKEY = auto()
    EXT_ADD_PLAYER_NAME = auto()
    EXT_ADD_ENTITY = auto()
    EXT_REMOVE_PLAYER_NAME = auto()
    ENV_SET_COLOR = auto()
    MAKE_SELECTION = auto()
    REMOVE_SELECTION = auto()
    SET_BLOCK_PERMISSION = auto()
    SET_MODEL = auto()
    ENV_SET_MAP_APPEARANCE = auto()
    ENV_SET_WEATHER = auto()
    HACK_CONTROL = auto()
    EXT_ADD_ENTITY2 = auto()
    PLAYER_CLICK = auto()
    DEFINE_BLOCK = auto()
    UNDEFINE_BLOCK = auto()
    DEFINE_BLOCK_EXT = auto()
    BULK_BLOCK_UPDATE = auto()
    SET_TEXT_COLOR = auto()
    ENV_SET_MAP_URL = auto()
    ENV_SET_MAP_PROPERTY = auto()
    SET_ENTITY_PROPERTY = auto()
    TWO_WAY_PING = auto()
    SET_INVENTORY_ORDER = auto()
    SET_HOTBAR = auto()
    SET_SPAWNPOINT = auto()
    VELOCITY_CONTROL = auto()
    DEFINE_EFFECT = auto()
    SPAWN_EFFECT = auto()
    DEFINE_MODEL = auto()
    DEFINE_MODEL_PART = auto()
    UNDEFINE_MODEL = auto()
    PLUGIN_MESSAGE = auto()
    ENTITY_TELEPORT_EXT = auto()
